repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^(backend/sam/.*\.yaml|infra/.*\.ya?ml)$  # Exclude CloudFormation templates
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
        args: [--line-length=120]

-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
    -   id: poetry-check
        files: ^pyproject\.toml$

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-no-eval
    -   id: python-use-type-annotations

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
    -   id: check-github-workflows
        files: ^\.github/workflows/

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]
        files: ^backend/

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        additional_dependencies: [
            boto3,
            botocore,
            httpx,
            nltk,
            openai,
            pinecone,
            pytest,
            pytest-cov,
            pytest-mock,
            requests
        ]
        pass_filenames: false
        always_run: true
        args: [backend/tests/]
