"""MartyChat Router for FastAPI.

Handles chatbot requests under `/api/v1/marty`.
"""

__author__ = ["Nikolai Alexander", "Doug Alexander"]
__email__ = "njalexander93@gmail.com, dalexander61@gmail.com"
__version__ = "1.0.0"
__date__ = "TBD"
__license__ = "Proprietary"
__copyright__ = "Copyright (c) 2025 MartyChat"

import logging
import openai
import requests
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from .model_loader import load_model

router = APIRouter()

class ChatRequest(BaseModel):
    """Schema for chat API request."""
    question: str
    user_id: str


def format_citations(citations: dict) -> str:
    """Formats citations with deduplication and clear formatting.

    Given a dictionary of citation IDs and corresponding sources, this function deduplicates the sources and formats.

    Args:
        citations (dict): A dictionary of citation IDs and corresponding sources.
    Returns:
        str: The formatted citations with deduplication.
    """
    # Create a dictionary of unique sources
    unique_sources = {}
    for cid, source in citations.items():
        source_key = source.strip().lower()
        if source_key not in unique_sources:
            unique_sources[source_key] = cid

    # Format citations using only unique sources
    formatted_citations = []
    for source_key, cid in unique_sources.items():
        original_source = citations[cid]
        formatted_citations.append(f"{cid}: {original_source}")

    return "\n".join(formatted_citations)

def generate_response_with_citations(question: str, context: str, system_prompt: str, citations: dict) -> str:
    """Generates a response with citations based on the provided context and question.

    Given a question, context, and citations, this function generates a response using an AI model and includes the
    provided citations.

    Args:
        question (str): The question asked by the user.
        context (str): The context from which the response should be generated.
        citations (dict): A dictionary of citation IDs and corresponding sources.
    Returns:
        str: The response generated by the AI model with citations.
    """

    prompt = f"""Based solely on the provided context, give a detailed and constructive response that highlights the value and contributions of the work. Do not include any information from outside the provided context.

    Context: {context}

    Question: {question}

    Requirements:
    1. Draw exclusively from the provided context
    2. Present the information in a positive, appreciative manner
    3. Use formal, professional language
    4. Include relevant citations for all claims
    5. If certain aspects cannot be addressed from the available context, acknowledge this professionally

    Available Citations:
    {format_citations(citations)}
    """

    # Generate response from OpenAI model
    model = load_model()
    response = openai.ChatCompletion.create(
        model=model["openai_model"],
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        temperature=model["temperature"]
    )
    response_text = response['choices'][0]['message']['content']

    # Ensure references are included
    if citations and "References:" not in response_text:
        response_text += "\n\nReferences:\n"
        for cid, source in citations.items():
            response_text += f"{cid}: {source}\n"

    return response_text

@router.post("/marty")
def generate_response(request: ChatRequest) -> dict:
    """Processes user input with history and citation support.

    This endpoint processes a user's question with historical context and citation support. It generates a response
    based on the provided context and citations. The response is generated using an AI model that follows specific
    guidelines for academic and research discussions.

    Args:
        request (ChatRequest): The request containing the user's question and user ID.
    Returns:
        dict: The response generated by the AI model.
    """
    # Extract the recent context from the conversation
    history_url = "https://your-aws-lambda-url/get-conversation-history"
    history_response = requests.post(history_url, json={"user_id": request.user_id, "history_length": 3}, timeout=30)
    history = history_response.json().get("history", [])

    # Prepare the context as a list of user inputs and system prompts
    recent_context = []
    if history:
        for message in history:
            if message["role"] == "system":
                recent_context.append(f"Assistant: {message['content']}")
            elif message["role"] == "user":
                recent_context.append(f"User: {message['content']}")

    if recent_context:
        context = "\n".join(recent_context)
        enhanced_query = f"Context from previous conversation: {context}\n\nCurrent question: {request.question}"
    else:
        enhanced_query = request.question

    # Analyze the query complexity
    complexity_url = "https://your-aws-lambda-url/analyze-query-complexity"
    complexity_response = requests.post(complexity_url, json={"query": enhanced_query}, timeout=30)
    k = complexity_response.json().get("k", 5)

    # Fetch similar documents from Pinecone
    pinecone_url = "https://your-aws-lambda-url/get-similar-docs"
    pinecone_response = requests.post(pinecone_url, json={"query": enhanced_query, "k": k}, timeout=30)
    pinecone_data = pinecone_response.json()

    # Extract content and citations
    citations = pinecone_data.get("citations", {})
    contexts = []
    for match in pinecone_data.get("matches", []):
        if match["score"] >= 0.45:
            contexts.append(f"{match['content']} {match['citation_id']}")
    combined_context = "\n\n".join(contexts)

    # Define the system prompt for the AI model
    system_prompt = """You are a knowledgeable assistant specializing in presenting research and academic work in a constructive and positive manner. When discussing Seligman's work:

    1. Focus on his contributions, insights, and the positive impact of his research
    2. Present his theories and findings in an appreciative, professional tone
    3. Use ONLY information provided in the context - do not reference external knowledge
    4. If asked about topics not covered in the provided context, politely indicate that the information is not available in the current document set
    5. Maintain academic rigor while highlighting the strengths and value of the work

    Format your response with:
    - Clear structure and logical flow
    - Professional, formal language
    - Full sentences and well-developed paragraphs
    - Proper citation integration
    """

    # Generate response with citations from the combined context and enhanced query.
    response = generate_response_with_citations(
        question=enhanced_query,
        context=combined_context,
        system_prompt=system_prompt,
        citations=citations
    )
    return {"response": response}
