# ========================================
# AWS CloudFormation Template for creating a DynamoDB table to store user profiles.
# Author: Nikolai Alexander
# Email: njalexander93@gmail.com
# Version: 1.0.0
# Date: TBD
# License: Proprietary
# Copyright (c) 2025 MartyChat
# ========================================

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    Default: "development"
    AllowedValues:
      - "development"
      - "staging"
      - "production"
    Description: "Specify the environment (Development, Staging, or Production)."

  TableName:
    Type: String
    Default: "martychat_users-development"
    Description: "DynamoDB table name, unique per environment."

Resources:
  MartyChatUsersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "martychat_users-${Environment}"
      BillingMode: "PAY_PER_REQUEST"

      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "organization"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"

      GlobalSecondaryIndexes:
        - IndexName: "OrganizationIndex"
          KeySchema:
            - AttributeName: "organization"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

      Tags:
        - Key: "project"
          Value: "martychat"
        - Key: "owner"
          Value: "nikolai_alexander"
        - Key: "created_by"
          Value: "CloudFormation"
        - Key: "environment"
          Value: !Ref Environment
        - Key: "service"
          Value: "DynamoDB"
        - Key: "purpose"
          Value: "ManageUserProfiles"

Outputs:
  DynamoDBTableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref MartyChatUsersTable
